// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI1KPliDFe48N-Ns48uRKLnMV37HxDgEA',
    appId: '1:204402729284:web:d82ee4198d8f0dd3483711',
    messagingSenderId: '204402729284',
    projectId: 'timelist-6fdbc',
    authDomain: 'timelist-6fdbc.firebaseapp.com',
    storageBucket: 'timelist-6fdbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwXA_OBO7CcajpGlwxhPeujafGVmpqQrk',
    appId: '1:204402729284:android:9cc0e1881110b31d483711',
    messagingSenderId: '204402729284',
    projectId: 'timelist-6fdbc',
    storageBucket: 'timelist-6fdbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-I01BFWjHAO2s3-B-br5fEOGYNgZU6A',
    appId: '1:204402729284:ios:e2060a661ca718fc483711',
    messagingSenderId: '204402729284',
    projectId: 'timelist-6fdbc',
    storageBucket: 'timelist-6fdbc.appspot.com',
    iosClientId: '204402729284-q8f3bqmitc6c1553iaei7lecv8fpsqk5.apps.googleusercontent.com',
    iosBundleId: 'com.yvonne.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-I01BFWjHAO2s3-B-br5fEOGYNgZU6A',
    appId: '1:204402729284:ios:e2060a661ca718fc483711',
    messagingSenderId: '204402729284',
    projectId: 'timelist-6fdbc',
    storageBucket: 'timelist-6fdbc.appspot.com',
    iosClientId: '204402729284-q8f3bqmitc6c1553iaei7lecv8fpsqk5.apps.googleusercontent.com',
    iosBundleId: 'com.yvonne.myapp',
  );
}
